;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet")
;;(add-to-list 'load-path nil)
;;(add-to-list 'load-path ".")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/common/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/cogre/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/contrib/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/quickpeek/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/semantic/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/srecode/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/tests/")
;;(add-to-list 'load-path "ctags/")
;;(add-to-list 'load-path "wisent/")
;;(add-to-list 'load-path "bovine/")
;;(add-to-list 'load-path "symref/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/speedbar/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/ede/")
;;(add-to-list 'load-path "~/.emacs.d/el-get/cedet/eieio/")
;;(add-to-list 'load-path "./")
;;(require 'cedet-autogen)
;; (require 'semantic)
;;(require 'cedet)

;; (semantic-load-enable-minimum-features)
;; (semantic-load-enable-code-helpers)
;; (semantic-load-enable-guady-code-helpers)
;; (semantic-load-enable-excessive-code-helpers)
;; (semantic-load-enable-semantic-debugging-helpers)

;; (global-set-key (kbd "M-n") 'semantic-ia-complete-symbol-menu)
;; (define-key c-mode-base-map (kbd "M-n") 'semantic-ia-complete-symbol-menu)

;;(require 'semantic-tag-folding nil 'noerror)
;;(global-semantic-tag-folding-mode 1)

;;(global-ede-mode t)

;;(require 'eassist nil 'noerror)