(add-to-list 'load-path "~/.emacs.d/el-get/color-theme/")
(require 'color-theme)
(color-theme-initialize)
;;(load-file "~/.emacs.d/el-get/color-theme-twilight/color-theme-twilight.el")
(load-file "~/.emacs.d/el-get/color-theme-chocolate-rain/color-theme-chocolate-rain.el")

;;(color-theme-twilight)
;;(color-theme-charcoal-black)
;;(color-theme-tango-2)
(color-theme-chocolate-rain)
